// @flow

export const USERS_NOTIFICATIONS_REQUEST: 'USERS_NOTIFICATIONS_REQUEST' =	'USERS_NOTIFICATIONS_REQUEST';
export const USERS_NOTIFICATIONS_SUCCESS: 'USERS_NOTIFICATIONS_SUCCESS' =	'USERS_NOTIFICATIONS_SUCCESS';
export const USERS_NOTIFICATIONS_FAIL: 'USERS_NOTIFICATIONS_FAIL' =	'USERS_NOTIFICATIONS_FAIL';

export const USERS_PUT_REQUEST: 'USERS_PUT_REQUEST' = 'USERS_PUT_REQUEST';
export const USERS_PUT_SUCCESS: 'USERS_PUT_SUCCESS' = 'USERS_PUT_SUCCESS';
export const USERS_PUT_FAIL: 'USERS_PUT_FAIL' = 'USERS_PUT_FAIL';

export const USERS_NOTIFICATIONS_UPDATE: 'USERS_NOTIFICATIONS_UPDATE' = 'USERS_NOTIFICATIONS_UPDATE';

export const USERS_NOTIFICATIONS_RESET: 'USERS_NOTIFICATIONS_RESET' = 'USERS_NOTIFICATIONS_RESET';
