// flow-typed signature: e293f0ac4ef653c48d4e02f8c7a8971f
// flow-typed version: <<STUB>>/craco-alias_v^2.1.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'craco-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'craco-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'craco-alias/plugin/create-overrider' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/debug' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/exit-with-error' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/extract-aliases' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/extract-aliases/index.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/extract-aliases/normalize-aliases' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/extract-aliases/normalize-aliases.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/generate-module-name-mapper' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/generate-module-name-mapper.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/helpers/escape-string-for-regexp' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/normalize-plugin-options' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/normalize-plugin-options.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-config-contents' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-config-contents.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-config-existence' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-config-existence.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-config' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-options' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check/check-options.test' {
  declare module.exports: any;
}

declare module 'craco-alias/plugin/pre-check' {
  declare module.exports: any;
}

// Filename aliases
declare module 'craco-alias/plugin/create-overrider.js' {
  declare module.exports: $Exports<'craco-alias/plugin/create-overrider'>;
}
declare module 'craco-alias/plugin/debug.js' {
  declare module.exports: $Exports<'craco-alias/plugin/debug'>;
}
declare module 'craco-alias/plugin/exit-with-error.js' {
  declare module.exports: $Exports<'craco-alias/plugin/exit-with-error'>;
}
declare module 'craco-alias/plugin/extract-aliases/index' {
  declare module.exports: $Exports<'craco-alias/plugin/extract-aliases'>;
}
declare module 'craco-alias/plugin/extract-aliases/index.js' {
  declare module.exports: $Exports<'craco-alias/plugin/extract-aliases'>;
}
declare module 'craco-alias/plugin/extract-aliases/index.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/extract-aliases/index.test'>;
}
declare module 'craco-alias/plugin/extract-aliases/normalize-aliases.js' {
  declare module.exports: $Exports<'craco-alias/plugin/extract-aliases/normalize-aliases'>;
}
declare module 'craco-alias/plugin/extract-aliases/normalize-aliases.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/extract-aliases/normalize-aliases.test'>;
}
declare module 'craco-alias/plugin/generate-module-name-mapper.js' {
  declare module.exports: $Exports<'craco-alias/plugin/generate-module-name-mapper'>;
}
declare module 'craco-alias/plugin/generate-module-name-mapper.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/generate-module-name-mapper.test'>;
}
declare module 'craco-alias/plugin/helpers/escape-string-for-regexp.js' {
  declare module.exports: $Exports<'craco-alias/plugin/helpers/escape-string-for-regexp'>;
}
declare module 'craco-alias/plugin/index' {
  declare module.exports: $Exports<'craco-alias/plugin'>;
}
declare module 'craco-alias/plugin/index.js' {
  declare module.exports: $Exports<'craco-alias/plugin'>;
}
declare module 'craco-alias/plugin/normalize-plugin-options.js' {
  declare module.exports: $Exports<'craco-alias/plugin/normalize-plugin-options'>;
}
declare module 'craco-alias/plugin/normalize-plugin-options.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/normalize-plugin-options.test'>;
}
declare module 'craco-alias/plugin/pre-check/check-config-contents.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-config-contents'>;
}
declare module 'craco-alias/plugin/pre-check/check-config-contents.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-config-contents.test'>;
}
declare module 'craco-alias/plugin/pre-check/check-config-existence.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-config-existence'>;
}
declare module 'craco-alias/plugin/pre-check/check-config-existence.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-config-existence.test'>;
}
declare module 'craco-alias/plugin/pre-check/check-config.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-config'>;
}
declare module 'craco-alias/plugin/pre-check/check-options.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-options'>;
}
declare module 'craco-alias/plugin/pre-check/check-options.test.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check/check-options.test'>;
}
declare module 'craco-alias/plugin/pre-check/index' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check'>;
}
declare module 'craco-alias/plugin/pre-check/index.js' {
  declare module.exports: $Exports<'craco-alias/plugin/pre-check'>;
}
