// flow-typed signature: 37016d34d26d4c30b57c45367a3931a5
// flow-typed version: <<STUB>>/date-fns_v2.11.0/flow_v0.119.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type Locale = {
  code?: string,
  formatDistance?: (...args: Array<any>) => any,
  formatRelative?: (...args: Array<any>) => any,
  localize?: {
    ordinalNumber: (...args: Array<any>) => any,
    era: (...args: Array<any>) => any,
    quarter: (...args: Array<any>) => any,
    month: (...args: Array<any>) => any,
    day: (...args: Array<any>) => any,
    dayPeriod: (...args: Array<any>) => any,
  },
  formatLong?: {
    date: (...args: Array<any>) => any,
    time: (...args: Array<any>) => any,
    dateTime: (...args: Array<any>) => any,
  },
  match?: {
    ordinalNumber: (...args: Array<any>) => any,
    era: (...args: Array<any>) => any,
    quarter: (...args: Array<any>) => any,
    month: (...args: Array<any>) => any,
    day: (...args: Array<any>) => any,
    dayPeriod: (...args: Array<any>) => any,
  },
  options?: {
    weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6,
    firstWeekContainsDate?: 1 | 2 | 3 | 4 | 5 | 6 | 7,
  },
}

declare module 'date-fns' {
  declare export function format(
    date: Date | number,
    format: string,
    options?: {
      locale?: Locale,
      weekStartsOn?: 0 | 1 | 2 | 3 | 4 | 5 | 6,
      firstWeekContainsDate?: number,
      useAdditionalWeekYearTokens?: boolean,
      useAdditionalDayOfYearTokens?: boolean,
    }
  ): string;
  declare export function formatISO(
    date: Date | number | string,
    options?: {
      format?: "extended" | "basic";
      representation?: "complete" | "date" | "time";
    }
  ): string;
  declare export function startOfDay(
    date: Date | number| string): Date;
  declare export function endOfDay(
    date: Date | number| string): Date;
    declare export function parseISO(
      date: Date | string | void): string;
}