// flow-typed signature: 28b4542bcc7786594dc492cd9378e933
// flow-typed version: <<STUB>>/lightweight-charts_v2.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lightweight-charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lightweight-charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lightweight-charts/dist/lightweight-charts.esm.development' {
  declare module.exports: any;
}

declare module 'lightweight-charts/dist/lightweight-charts.esm.production' {
  declare module.exports: any;
}

declare module 'lightweight-charts/dist/lightweight-charts.standalone.development' {
  declare module.exports: any;
}

declare module 'lightweight-charts/dist/lightweight-charts.standalone.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lightweight-charts/dist/lightweight-charts.esm.development.js' {
  declare module.exports: $Exports<'lightweight-charts/dist/lightweight-charts.esm.development'>;
}
declare module 'lightweight-charts/dist/lightweight-charts.esm.production.js' {
  declare module.exports: $Exports<'lightweight-charts/dist/lightweight-charts.esm.production'>;
}
declare module 'lightweight-charts/dist/lightweight-charts.standalone.development.js' {
  declare module.exports: $Exports<'lightweight-charts/dist/lightweight-charts.standalone.development'>;
}
declare module 'lightweight-charts/dist/lightweight-charts.standalone.production.js' {
  declare module.exports: $Exports<'lightweight-charts/dist/lightweight-charts.standalone.production'>;
}
declare module 'lightweight-charts/index' {
  declare module.exports: $Exports<'lightweight-charts'>;
}
declare module 'lightweight-charts/index.js' {
  declare module.exports: $Exports<'lightweight-charts'>;
}
