// flow-typed signature: 66692c97e4342d4a38f466f004cf0420

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-hash' {
  declare module.exports: any;
}
