// flow-typed signature: 774b7e01e966c8036be63305f0838884
// flow-typed version: <<STUB>>/react-json-view_v>=10/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-view' {
  declare module.exports: any;
}