// flow-typed signature: 113db3c116808e0bdafa08e609f1e55c
// flow-typed version: <<STUB>>/reset-css_v^5.0.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
