// flow-typed signature: c0ccce53e7e1d350299aa6662191f591
// flow-typed version: <<STUB>>/stylelint-webpack-plugin_v^1.2.3/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist/getOptions' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist/LintDirtyModulesPlugin' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist/linter' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist/StylelintError' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/cjs'>;
}
declare module 'stylelint-webpack-plugin/dist/getOptions.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/getOptions'>;
}
declare module 'stylelint-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist'>;
}
declare module 'stylelint-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist'>;
}
declare module 'stylelint-webpack-plugin/dist/LintDirtyModulesPlugin.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/LintDirtyModulesPlugin'>;
}
declare module 'stylelint-webpack-plugin/dist/linter.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/linter'>;
}
declare module 'stylelint-webpack-plugin/dist/StylelintError.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/StylelintError'>;
}
declare module 'stylelint-webpack-plugin/dist/utils.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/dist/utils'>;
}
