// flow-typed signature: 501e0a18aae7cda9c5b2f470cd683183
// flow-typed version: <<STUB>>/typesocket_v1.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typesocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typesocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typesocket/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typesocket/lib/index' {
  declare module.exports: $Exports<'typesocket/lib'>;
}
declare module 'typesocket/lib/index.js' {
  declare module.exports: $Exports<'typesocket/lib'>;
}
