// @flow

export const PROFITS_REQUEST: 'PROFITS_REQUEST' =	'PROFITS_REQUEST';
export const PROFITS_SUCCESS: 'PROFITS_SUCCESS' =	'PROFITS_SUCCESS';
export const PROFITS_FAIL: 'PROFITS_FAIL' =	'PROFITS_FAIL';
