// flow-typed signature: bdd893c0f0995135139a89f7910b36d0
// flow-typed version: <<STUB>>/@craco/craco_v^5.6.3/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@craco/craco'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@craco/craco' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@craco/craco/bin/craco' {
  declare module.exports: any;
}

declare module '@craco/craco/bin/jest' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/args' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/config' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/cra' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/dev-server-utils' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/dev-server' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/plugins' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/api' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/jest-babel-transform' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/merge-jest-config' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/test/override' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/api' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/babel' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/eslint' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/merge-webpack-config' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/override' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/style/css' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/style/postcss' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/style/sass' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/style/style' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/features/webpack/typescript' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/loaders' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/logger' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/paths' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/plugin-utils' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/user-config-utils' {
  declare module.exports: any;
}

declare module '@craco/craco/lib/utils' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/build' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/start' {
  declare module.exports: any;
}

declare module '@craco/craco/scripts/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@craco/craco/bin/craco.js' {
  declare module.exports: $Exports<'@craco/craco/bin/craco'>;
}
declare module '@craco/craco/bin/jest.js' {
  declare module.exports: $Exports<'@craco/craco/bin/jest'>;
}
declare module '@craco/craco/index' {
  declare module.exports: $Exports<'@craco/craco'>;
}
declare module '@craco/craco/index.js' {
  declare module.exports: $Exports<'@craco/craco'>;
}
declare module '@craco/craco/lib/args.js' {
  declare module.exports: $Exports<'@craco/craco/lib/args'>;
}
declare module '@craco/craco/lib/config.js' {
  declare module.exports: $Exports<'@craco/craco/lib/config'>;
}
declare module '@craco/craco/lib/cra.js' {
  declare module.exports: $Exports<'@craco/craco/lib/cra'>;
}
declare module '@craco/craco/lib/features/dev-server-utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/dev-server-utils'>;
}
declare module '@craco/craco/lib/features/dev-server.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/dev-server'>;
}
declare module '@craco/craco/lib/features/plugins.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/plugins'>;
}
declare module '@craco/craco/lib/features/test/api.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/api'>;
}
declare module '@craco/craco/lib/features/test/jest-babel-transform.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/jest-babel-transform'>;
}
declare module '@craco/craco/lib/features/test/merge-jest-config.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/merge-jest-config'>;
}
declare module '@craco/craco/lib/features/test/override.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/test/override'>;
}
declare module '@craco/craco/lib/features/webpack/api.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/api'>;
}
declare module '@craco/craco/lib/features/webpack/babel.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/babel'>;
}
declare module '@craco/craco/lib/features/webpack/eslint.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/eslint'>;
}
declare module '@craco/craco/lib/features/webpack/merge-webpack-config.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/merge-webpack-config'>;
}
declare module '@craco/craco/lib/features/webpack/override.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/override'>;
}
declare module '@craco/craco/lib/features/webpack/style/css.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/style/css'>;
}
declare module '@craco/craco/lib/features/webpack/style/postcss.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/style/postcss'>;
}
declare module '@craco/craco/lib/features/webpack/style/sass.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/style/sass'>;
}
declare module '@craco/craco/lib/features/webpack/style/style.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/style/style'>;
}
declare module '@craco/craco/lib/features/webpack/typescript.js' {
  declare module.exports: $Exports<'@craco/craco/lib/features/webpack/typescript'>;
}
declare module '@craco/craco/lib/loaders.js' {
  declare module.exports: $Exports<'@craco/craco/lib/loaders'>;
}
declare module '@craco/craco/lib/logger.js' {
  declare module.exports: $Exports<'@craco/craco/lib/logger'>;
}
declare module '@craco/craco/lib/paths.js' {
  declare module.exports: $Exports<'@craco/craco/lib/paths'>;
}
declare module '@craco/craco/lib/plugin-utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/plugin-utils'>;
}
declare module '@craco/craco/lib/user-config-utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/user-config-utils'>;
}
declare module '@craco/craco/lib/utils.js' {
  declare module.exports: $Exports<'@craco/craco/lib/utils'>;
}
declare module '@craco/craco/scripts/build.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/build'>;
}
declare module '@craco/craco/scripts/start.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/start'>;
}
declare module '@craco/craco/scripts/test.js' {
  declare module.exports: $Exports<'@craco/craco/scripts/test'>;
}
