// @flow

export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST';
export const ACCOUNTS_SUCCESS = 'ACCOUNTS_SUCCESS';
export const ACCOUNTS_FAIL = 'ACCOUNTS_FAIL';


export const ACCOUNT_PROFILES_REQUEST = 'ACCOUNT_PROFILES_REQUEST';
export const ACCOUNT_PROFILES_SUCCESS = 'ACCOUNT_PROFILES_SUCCESS';
export const ACCOUNT_PROFILES_FAIL = 'ACCOUNT_PROFILES_FAIL';

export const ACCOUNT_BALANCES_REQUEST = 'ACCOUNT_BALANCES_REQUEST';
export const ACCOUNT_BALANCES_SUCCESS = 'ACCOUNT_BALANCES_SUCCESS';
export const ACCOUNT_BALANCES_FAIL = 'ACCOUNT_BALANCES_FAIL';
