// @flow
export const SET_NOTIFICATION: 'SET_NOTIFICATION' = 'SET_NOTIFICATION';
export const SET_SUCCESS_NOTIFICATION: 'SET_SUCCESS_NOTIFICATION' = 'SET_SUCCESS_NOTIFICATION';
export const SET_ERROR_NOTIFICATION: 'SET_ERROR_NOTIFICATION' = 'SET_ERROR_NOTIFICATION';
export const SET_NORMAL_NOTIFICATION: 'SET_NORMAL_NOTIFICATION' = 'SET_NORMAL_NOTIFICATION';
export const GETTING_NOTIFICATION: 'GETTING_NOTIFICATION' = 'GETTING_NOTIFICATION';
export const RESET_NOTIFICATION: 'RESET_NOTIFICATION' = 'RESET_NOTIFICATION';
