// @flow

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REQ_LOGIN = 'AUTH_REQ_LOGIN';
export const AUTH_REQ_LOGIN_SEND = 'AUTH_REQ_LOGIN_SEND';
export const AUTH_REQ_LOGIN_SUCCESS = 'AUTH_REQ_LOGIN_SUCCESS';
export const AUTH_REQ_LOGIN_ERROR = 'AUTH_REQ_LOGIN_ERROR';

export const AUTH_REQ_AUTH = 'AUTH_REQ_AUTH';
export const AUTH_REQ_AUTH_SEND = 'AUTH_REQ_AUTH_SEND';
export const AUTH_REQ_AUTH_SUCCESS = 'AUTH_REQ_AUTH_SUCCESS';
export const AUTH_REQ_AUTH_ERROR = 'AUTH_REQ_AUTH_ERROR';

export const AUTH_RESEND_AUTH_CODE = 'AUTH_RESEND_AUTH_CODE';

export const CHECK_TOKEN = 'CHECK_TOKEN';
