// @flow

export const BASE_ACCOUNT_CREATE_REQUEST: 'BASE_ACCOUNT_CREATE_REQUEST' = 'BASE_ACCOUNT_CREATE_REQUEST';
export const BASE_ACCOUNT_CREATE_SUCCESS: 'BASE_ACCOUNT_CREATE_SUCCESS' = 'BASE_ACCOUNT_CREATE_SUCCESS';
export const BASE_ACCOUNT_CREATE_FAIL: 'BASE_ACCOUNT_CREATE_FAIL' = 'BASE_ACCOUNT_CREATE_FAIL';

export const BASE_ACCOUNT_TABLE_REQUEST: 'BASE_ACCOUNT_TABLE_REQUEST' = 'BASE_ACCOUNT_TABLE_REQUEST';
export const BASE_ACCOUNT_TABLE_SUCCESS: 'BASE_ACCOUNT_TABLE_SUCCESS' = 'BASE_ACCOUNT_TABLE_SUCCESS';
export const BASE_ACCOUNT_TABLE_FAIL: 'BASE_ACCOUNT_TABLE_FAIL' = 'BASE_ACCOUNT_TABLE_FAIL';

export const BASE_ACCOUNT_PROFILES_REQUEST: 'BASE_ACCOUNT_PROFILES_REQUEST' = 'BASE_ACCOUNT_PROFILES_REQUEST';
export const BASE_ACCOUNT_PROFILES_SUCCESS: 'BASE_ACCOUNT_PROFILES_SUCCESS' = 'BASE_ACCOUNT_PROFILES_SUCCESS';
export const BASE_ACCOUNT_PROFILES_FAIL: 'BASE_ACCOUNT_PROFILES_FAIL' = 'BASE_ACCOUNT_PROFILES_FAIL';

export const BASE_ACCOUNT_BALANCES_REQUEST: 'BASE_ACCOUNT_BALANCES_REQUEST' = 'BASE_ACCOUNT_BALANCES_REQUEST';
export const BASE_ACCOUNT_BALANCES_SUCCESS: 'BASE_ACCOUNT_BALANCES_SUCCESS' = 'BASE_ACCOUNT_BALANCES_SUCCESS';
export const BASE_ACCOUNT_BALANCES_FAIL: 'BASE_ACCOUNT_BALANCES_FAIL' = 'BASE_ACCOUNT_BALANCES_FAIL';

export const BASE_ACCOUNT_UPDATE_REQUEST: 'BASE_ACCOUNT_UPDATE_REQUEST' = 'BASE_ACCOUNT_UPDATE_REQUEST';
export const BASE_ACCOUNT_UPDATE_SUCCESS: 'BASE_ACCOUNT_UPDATE_SUCCESS' = 'BASE_ACCOUNT_UPDATE_SUCCESS';
export const BASE_ACCOUNT_UPDATE_FAIL: 'BASE_ACCOUNT_UPDATE_FAIL' = 'BASE_ACCOUNT_UPDATE_FAIL';
